### ISSUE TITLE
Feature Request: Abbreviation 

### ISSUE THREAD

**Issue by Xanaxus** [chrisgrieser/obsidian-extra-md-commands#4]
**Feature Requested**
Can we also get the feature of abbreviation, which is available in [Markdown Extra](https://nancym.tumblr.com/post/59594358553/links-footnotes-and-abbreviations-in-markdown)
```
IMHO, the word *abbreviation* is a bit of a misnomer in this context.
:
*[IMHO]: In my humble opinion
*[misnomer]: inappropriate 

```
**Relevant Screenshots**
![image](https://user-images.githubusercontent.com/53279068/150983654-2dcbd8d8-2578-41e7-87bd-68aba5534e11.png)

**Checklist**
- [x] I have checked that there isn't [another hotkey plugin](https://publish.obsidian.md/hub/02+-+Community+Expansions/02.01+Plugins+by+Category/Plugins+that+add+or+manage+hotkeys) that does what I want.

**Comment by chrisgrieser** [comment]
I assume this is resolved?
https://discord.com/channels/686053708261228577/722584061087842365/935515803133050930

**Comment by Xanaxus** [comment]
As individuals who use this, for now will need to create a folder for abbreviation then create a new note every time, instead of just adding a single line. I feel it's counterproductive, and it won't be nice to have just a single note for just an abbreviation.

**Comment by chrisgrieser** [comment]
I am not sure I follow what you mean by folders. 

Anyway, the `<abrv>` syntax is easy to add, if that's the only thing that matters?

**Comment by namtrah** [comment]
I would also like to ask for <abrv> Markdown Extra syntax like described in [PHP Markdown Extra](https://michelf.ca/projects/php-markdown/extra/#abbr).

**Comment by chrisgrieser** [comment]
@namtrah As I am not familiar with the Syntax (it's also not supported by Obsidian I believe?), could you elaborate how that works?

`Lorem ipsum denoc`, which the word "Lorem" selected should become `*[Lorem]: ipsum donec`, is that it?

**Comment by Xanaxus** [comment]
@chrisgrieser yes only the word "Loprem" will highlighted in the similar fashion that the syntax `<abrv>` will do. 

And yes we can do the same via the `<abrv>` but it will be an repetitive task when this syntax `*[Lorem]: ipsum donec` will do it for the whole document/note, instead of us resusing the `<abrv>` syntax everytime we use the word `Lorem`

  This is well explained in the link which is provided by @namtrah 
> I would also like to ask for Markdown Extra syntax like described in [PHP Markdown Extra](https://michelf.ca/projects/php-markdown/extra/#abbr).

@namtrah thanks for that beautiful document.

**Comment by chrisgrieser** [comment]
okay then, as I don't wanna get this wrong (not being familiar with php markdown) could one of you simply tell me what should be put in front of the selection and what should be put at the back of the selection? Then I'll add it.

**Comment by namtrah** [comment]
Let me make an example (taken from https://www.w3schools.com/tags/tag_abbr.asp and modified for `Markdown Extra` format


All instances of the word "WHO" in the following example

> The WHO was founded in 1948. WHO's primary role is to direct international health within the United Nations' system and to lead partners in global health responses.

**Should** be replaced with the following:

> The <abbr title="World Health Organization">WHO</abbr> was founded in 1948. <abbr title="World Health Organization">WHO</abbr>'s primary role is to direct international health within the United Nations' system and to lead partners in global health responses.

When
> *[WHO]: World Health Organization

Exists anywhere in the same file (with the '*' starting as the first character of a line)

That way, whenever I use an abbreviation like ABBR, it will be replaced with <abbr title="...">ABBR</abrv> in my single file.

Is that clearer?

**Comment by chrisgrieser** [comment]
Ah yes, now I understand. However, that is far outside the scope of the plugin, which only wraps text in static markup, not dynamic markup like your case. 

Implementing your feature would require a good amount of work for a feature that very few users will be interested in (abbreviation md not being part of Obsidian without html). 

Therefore, I don't think that I will implement this, sorry. :(

However, you could look into the Longform plugin's compile feature or a templater script to get what you want.
